In [2]:
from collections import defaultdict
import numpy as np
from pathlib import Path
import argparse
import talib as ta
import glob
import pandas as pd

In [3]:
train_data = pd.read_csv('train_data_50.csv')
# change date into datetime objects
train_data['Date'] = pd.to_datetime(train_data['Date'])

# set indexes 
train_data.set_index(["Ticker", "Date"], inplace=True)
tickers = sorted(train_data.index.get_level_values('Ticker').unique())

open_prices = []

In [4]:
train_data

                        Open       High        Low      Close  Adj Close  \
Ticker Date
ZJ     2015-07-06   5.699535   5.758382   5.695429   5.747890   5.193889
       2015-07-07   5.742872   5.754733   5.646161   5.733748   5.181111
       2015-07-08   5.678550   5.685849   5.590051   5.591420   5.052501
       2015-07-09   5.649811   5.659391   5.438599   5.477374   4.949447
       2015-07-10   5.562680   5.649811   5.529379   5.623808   5.081768
...                      ...        ...        ...        ...        ...
ZA     2021-04-05  10.455685  10.459335  10.244017  10.309707   9.270878
       2021-04-06  10.371748  10.499479  10.265913  10.280512   9.244624
       2021-04-07  10.289635  10.358975  10.262265  10.326130   9.285647
       2021-04-08  10.205698  10.233069  10.094389  10.218471   9.188834
       2021-04-09  10.218471  10.298759  10.132709  10.194749   9.167504

                      Volume
Ticker Date
ZJ     2015-07-06  112241600
       2015-07-07  187787200
       2015-07-08  243046400
       2015-07-09  314380000
       2015-07-10  245418000
...                      ...
ZA     2021-04-05   23264800
       2021-04-06   18926300
       2021-04-07   22385000
       2021-04-08   21999300
       2021-04-09   20020700

[72600 rows x 6 columns]

In [5]:
# numpy array of all stocks and their close prices
for ticker in tickers:
    stock_close_data = train_data.loc[ticker]["Open"]
    open_prices.append(stock_close_data.values)

open_prices = np.stack(open_prices)
print(stock_close_data)
print(open_prices.shape)
print(open_prices)

# empty array for trades
trades = np.zeros_like(open_prices)
trades



print(trades)

Date
2015-07-06    20.121263
2015-07-07    20.385850
2015-07-08    20.385850
2015-07-09    20.495333
2015-07-10    20.559198
                ...
2021-04-05    56.537339
2021-04-06    57.225259
2021-04-07    57.084757
2021-04-08    57.059214
2021-04-09    57.546413
Name: Open, Length: 1452, dtype: float64
(50, 1452)
[[17.04294995 17.25096871 16.96448663 ... 67.35797313 68.06231506
  68.62432851]
 [12.20377331 12.24209241 12.04319784 ... 27.93657064 28.10079496
  28.43107009]
 [27.76139563 28.32888582 28.12086706 ... 45.28424827 45.45394932
  45.20031238]
 ...
 [12.73111928 12.80593376 12.77856257 ... 40.5016405  40.69141088
  40.9340999 ]
 [ 8.02149948  8.0908393   8.10908629 ... 45.21855798 46.12362377
  46.14186937]
 [20.12126341 20.38584965 20.38584965 ... 57.08475709 57.0592138
  57.54641278]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [6]:

for ticker in tickers:
    n = ta.AD(train_data.loc['ZJ']["High"], train_data.loc['ZJ']["Low"], train_data.loc['ZJ']["Close"], train_data.loc['ZJ']["Volume"])
    plt.plot(n.index,n.values, label=f'{ticker}')


plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Stock Prices')
plt.legend()
plt.show()

NameError: name 'plt' is not defined